from __future__ import annotations

from senate_audio_audit.models import AcousticMetrics, AnalysisResult, VividnessResult


def make_result(
    *,
    run_id: str = "run-1",
    run_key: str = "key-1",
    supersedes: str | None = None,
    filename: str = "sample.mp3",
    vividness_score: int | None = 4,
) -> AnalysisResult:
    metrics = AcousticMetrics(
        active_speech_median_dbfs=-18.0,
        active_speech_p95_dbfs=-10.0,
        clipping_fraction=0.0,
        median_speech_rate_wpm=120.0,
        median_pause_ratio=0.2,
        f0_variation_semitones=1.0,
        overlap_fraction=None,
        anonymous_speaker_count=None,
        active_speech_duration_ms=8000,
        speech_ratio=0.8,
        activity_method="test",
        activity_threshold_dbfs=-40.0,
        activity_noise_floor_dbfs=-60.0,
        channel_strategy="mono",
        f0_median_hz=200.0,
    )
    return AnalysisResult(
        schema_version="0.1.0",
        artifact_role="per_audio_latest_metrics",
        run_id=run_id,
        run_key=run_key,
        supersedes_run_id=supersedes,
        analysis_status="completed",
        created_at="2026-09-24T12:00:00Z",
        history={
            "jsonl": "sample.metrics.history.jsonl",
            "text": "sample.metrics.history.txt",
        },
        source={
            "source_id": "sample",
            "filename": filename,
            "path": f"/tmp/{filename}",
            "sha256": "a" * 64,
            "duration_ms": 10000,
            "size_bytes": 100,
            "format_name": "wav",
            "has_video": False,
            "rights_status": "approved_test",
            "permission_reference": "test",
            "metrics_filename": "sample.metrics.txt",
            "metrics_json": "sample.metrics.json",
            "metrics_text": "sample.metrics.txt",
        },
        scope={"start_ms": 0, "end_ms": 10000, "language": "fr"},
        pipeline={
            "version": "0.1.0",
            "config_hash": "config",
            "model_manifest_hash": "models",
            "models": {},
        },
        quality={
            "overall": "good",
            "activity_method": "test",
            "activity_confidence": "high",
            "transcript": "srt",
            "transcript_path": "/tmp/sample.srt",
            "transcript_sha256": "b" * 64,
            "transcript_alignment": "test",
            "diarization": "not_enabled",
            "channel_strategy": "mono",
            "channel_metrics": {},
            "warnings": [],
        },
        measurements=metrics,
        summary={
            "speech_present": "yes",
            "speech_ratio": 0.8,
            "candidate_event_count": 0,
            "status_note": "test snapshot",
        },
        vividness=VividnessResult(
            score=vividness_score,
            expected_rating=float(vividness_score or 0),
            status="provisional_rubric" if vividness_score is not None else "not_assessable",
            confidence_band="medium",
            prediction_interval_80=None,
            components={"peak": 0.4},
            explanation="Test snapshot",
        ),
        events=(),
        speaker_summaries=(),
        errors=(),
    )
